simple-cdd-meta: Introduce di_chroot_cleanup() helper
At the time of simple-cdd-profiles postinst phase, where profiles
.postinst executed via in-target debian-installer helper
debian-installer-utils tweaks that prevent installed packages postinst
scripts from starting services via invoke-rc.d(8) and/or
start-stop-daemon(8) helpers.

Thus snapshots of installed system (e.g. with btrfs-filesystem(8)
snapshot feature to be reused as rootfs for LXC) taken during
simple-cdd-profiles postinst phase will prevent from start all services
inside containers.

Introduce di_chroot_cleanup() helper that is based on apt-setup and
debian-installer-utils code to cleanup snapshots add address above
issue.

Signed-off-by: Serhey Popovych <serhe.popovych@gmail.com>

diff --git a/debian/templates/distro.postinst b/debian/templates/distro.postinst
--- a/debian/templates/distro.postinst
+++ b/debian/templates/distro.postinst
@@ -462,6 +462,29 @@ ssh_copy_id()
     fi
 }
 
+## Debian-installer helpers
+
+# Usage: di_chroot_cleanup <root>
+di_chroot_cleanup()
+{
+    local func="${FUNCNAME:-di_chroot_cleanup}"
+
+    local root="${1:?missing 1st arg to ${func}() <root>}"
+    local t f
+
+    ## Adopted from apt-setup/generators/40cdrom::chroot_cleanup_localmounts()
+
+    rm -f "$root/usr/sbin/policy-rc.d" ||:
+
+    # start-stop-daemon
+    t="$root/sbin/start-stop-daemon" && f="$t.REAL"
+    [ ! -x "$f" ] || mv -f "$f" "$t" ||:
+
+    # initctl
+    t="$root/sbin/initctl" && f="$t.REAL"
+    [ ! -x "$f" ] || mv -f "$f" "$t" ||:
+}
+
 ## Initial setup based on distro
 
 eval $(
