simple-cdd-meta/debian: Add option to enable systemd_cleanup_unit()
It is inappropriate to remove directives of unit file for recent
version of systemd as this may cause these units to malfunction.

Turn off this removal by default to avoid modifying unit files and
turn on for cases when such cleanup is really necessary (usually old
distros like Debian GNU/Linux 7.x (wheezy)).

Signed-off-by: Serhey Popovych <serhe.popovych@gmail.com>

diff --git a/debian/templates/distro.postinst b/debian/templates/distro.postinst
--- a/debian/templates/distro.postinst
+++ b/debian/templates/distro.postinst
@@ -187,6 +187,9 @@ systemd_etc_unit='/etc/systemd/system'
 # Usage: systemd_unit_cleanup <unit1> <unit2> ...
 systemd_unit_cleanup()
 {
+    # Do cleanup if enabled.
+    [ -n "${systemd_do_unit_cleanup+x}" ] || return 0
+
     local func="${FUNCNAME:-systemd_unit_cleanup}"
 
     local u="${systemd_unit:-$systemd_lib_unit}"
